---
version: '3.0'
services:
  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883" # MQTT Topic
      - "9001:9001" # HTTP/Websocket
  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - "8086:8086" # HTTP API
      - "2003:2003" # Graphite Support
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
#      - data:/var/lib/influxdb
      - ./influxdata:/var/lib/influxdb
  telegraf:
    image: telegraf:latest
    restart: always
    ports:
      - "8125:8125" # StatsD
      - "8092:8092" # UDP
      - "8094:8094" # TCP
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - gdata:/var/lib/grafana

volumes:
#  data:
  gdata:


  
